#!/usr/bin/env python3
"""Compare JR-100 PCM generated by the local machine and BrowserCore."""

from __future__ import annotations

import argparse
from array import array
import json
from pathlib import Path

from jr100emu.browser import BrowserCore
from jr100emu.jr100.computer import JR100Computer


def _active_segments(samples: array, window: int = 32) -> list[array]:
    active_windows = [
        any(samples[index : index + window]) for index in range(0, len(samples), window)
    ]
    segments: list[array] = []
    start: int | None = None
    for index, active in enumerate(active_windows + [False]):
        if active and start is None:
            start = index * window
        elif not active and start is not None:
            segments.append(samples[start : min(index * window, len(samples))])
            start = None
    return segments


def _estimated_frequency(samples: array, sample_rate: int = 44100) -> float:
    signs = [sample > 0 for sample in samples if sample != 0]
    crossings = sum(left != right for left, right in zip(signs, signs[1:]))
    return crossings * sample_rate / (2.0 * len(samples)) if samples else 0.0


def _set_cells(
    browser: BrowserCore,
    local: JR100Computer,
    cells: tuple[tuple[int, int], ...],
) -> None:
    browser.clear_keys()
    local.hardware.keyboard.clear()
    for row, bit in cells:
        browser.set_key(row, bit, True)
        local.hardware.keyboard.press(row, bit)


def _key_for_character(
    browser: BrowserCore,
    character: str,
) -> tuple[tuple[int, int], bool]:
    cells = [
        (row, bit)
        for row in range(9)
        for bit in range(5)
        if (row, bit) not in {(0, 0), (0, 1)}
    ]
    for shifted, table in (
        (False, browser.normal_key_codes()),
        (True, browser.shift_key_codes()),
    ):
        for cell, candidate in zip(cells, table):
            if candidate == ord(character):
                return cell, shifted
    raise ValueError(f"character cannot be typed on JR-100 keyboard: {character!r}")


def _advance_pair(
    browser: BrowserCore,
    local: JR100Computer,
    browser_samples: array,
    local_samples: array,
    frames: int,
) -> None:
    for _ in range(frames):
        browser.run_frame()
        browser_samples.extend(browser.audio_buffer())
        local.tick(BrowserCore.CYCLES_PER_FRAME)
        local_samples.extend(local.hardware.sound_processor.drain_samples())


def _type_command(
    browser: BrowserCore,
    local: JR100Computer,
    browser_samples: array,
    local_samples: array,
    command: str,
) -> None:
    _set_cells(browser, local, ())
    _advance_pair(browser, local, browser_samples, local_samples, 100)
    for character in command + "\r":
        cell, shifted = _key_for_character(browser, character)
        modifier = ((0, 1),) if shifted else ()
        if shifted:
            _set_cells(browser, local, modifier)
            _advance_pair(browser, local, browser_samples, local_samples, 4)
            _set_cells(browser, local, modifier + (cell,))
            _advance_pair(browser, local, browser_samples, local_samples, 8)
            _set_cells(browser, local, modifier)
            _advance_pair(browser, local, browser_samples, local_samples, 4)
        else:
            _set_cells(browser, local, (cell,))
            _advance_pair(browser, local, browser_samples, local_samples, 8)
        _set_cells(browser, local, ())
        _advance_pair(browser, local, browser_samples, local_samples, 6)
    _set_cells(browser, local, ())


def compare(rom_path: Path, program_path: Path, frames: int) -> dict[str, object]:
    rom_bytes = rom_path.read_bytes()
    program_bytes = program_path.read_bytes()
    browser = BrowserCore(rom_bytes)
    local = JR100Computer(
        rom_path=rom_path,
        enable_audio=False,
        capture_audio=True,
        allow_implicit_rom=False,
    )
    browser_samples = array("h")
    local_samples = array("h")

    browser_info = browser.computer.load_user_program_bytes(
        program_bytes,
        filename=program_path.name,
    )
    local_info = local.load_user_program_bytes(
        program_bytes,
        filename=program_path.name,
    )

    # BrowserCore and JR100Computer both reset at construction time. Advance
    # two frames after loading so any reset event is applied before typing.
    _advance_pair(browser, local, browser_samples, local_samples, 2)
    browser.audio_buffer()
    local.hardware.sound_processor.drain_samples()
    del browser_samples[:]
    del local_samples[:]
    browser.computer.hardware.sound_processor.history.clear()
    local.hardware.sound_processor.history.clear()

    if program_path.suffix.lower() in {".bas", ".txt"}:
        command = "RUN"
    else:
        if browser_info.entry_point is None or local_info.entry_point is None:
            raise RuntimeError("machine program has no entry point")
        if browser_info.entry_point != local_info.entry_point:
            raise RuntimeError("local and browser entry points differ")
        command = f"A=USR(${browser_info.entry_point:04X})"
    _type_command(browser, local, browser_samples, local_samples, command)
    _advance_pair(browser, local, browser_samples, local_samples, frames)

    common_length = min(len(browser_samples), len(local_samples))
    differences = [
        abs(browser_samples[index] - local_samples[index])
        for index in range(common_length)
    ]
    browser_segments = _active_segments(browser_samples)
    local_segments = _active_segments(local_samples)
    browser_frequencies = [
        round(values[1], 3)
        for name, values in browser.computer.hardware.sound_processor.history
        if name == "set_frequency"
    ]
    local_frequencies = [
        round(values[1], 3)
        for name, values in local.hardware.sound_processor.history
        if name == "set_frequency"
    ]
    return {
        "program": str(program_path),
        "frames": frames,
        "browserSamples": len(browser_samples),
        "localSamples": len(local_samples),
        "commonSamples": common_length,
        "sampleCountDelta": abs(len(browser_samples) - len(local_samples)),
        "sampleCountRatio": round(
            abs(len(browser_samples) - len(local_samples))
            / max(len(browser_samples), len(local_samples), 1),
            6,
        ),
        "exactCommonSamples": sum(value == 0 for value in differences),
        "maxAbsDifference": max(differences, default=0),
        "browserSegments": len(browser_segments),
        "localSegments": len(local_segments),
        "frequencyHistoryEqual": browser_frequencies == local_frequencies,
        "browserFrequencyHistory": browser_frequencies[:24],
        "localFrequencyHistory": local_frequencies[:24],
        "browserFrequencies": [
            round(_estimated_frequency(segment), 1) for segment in browser_segments[:12]
        ],
        "localFrequencies": [
            round(_estimated_frequency(segment), 1) for segment in local_segments[:12]
        ],
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rom", type=Path, default=Path("datas/jr100rom.prg"))
    parser.add_argument(
        "program",
        type=Path,
        nargs="*",
        default=[Path("datas/sound_scale.prg"), Path("datas/twinkle_star.bas")],
    )
    parser.add_argument("--frames", type=int, default=1200)
    args = parser.parse_args()
    if args.frames <= 0:
        parser.error("--frames must be positive")
    passed = True
    for program in args.program:
        result = compare(args.rom, program, args.frames)
        print(json.dumps(result, sort_keys=True))
        passed = passed and bool(
            result["frequencyHistoryEqual"]
            and result["browserSegments"] == result["localSegments"]
            and result["sampleCountRatio"] <= 0.01
        )
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
